// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalyticsRunTotalTimesModel dco_decode_analytics_run_total_times_model(
    dynamic raw,
  );

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  RunModel dco_decode_box_autoadd_run_model(dynamic raw);

  @protected
  RunTimesResponse dco_decode_box_autoadd_run_times_response(dynamic raw);

  @protected
  TimeTypeModel dco_decode_box_autoadd_time_type_model(dynamic raw);

  @protected
  DeleteRunResult dco_decode_delete_run_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InitializeParserOutcome dco_decode_initialize_parser_outcome(dynamic raw);

  @protected
  LegBreakModel dco_decode_leg_break_model(dynamic raw);

  @protected
  LegPositionEnum dco_decode_leg_position_enum(dynamic raw);

  @protected
  List<AnalyticsRunTotalTimesModel>
  dco_decode_list_analytics_run_total_times_model(dynamic raw);

  @protected
  List<LegBreakModel> dco_decode_list_leg_break_model(dynamic raw);

  @protected
  List<PhaseModel> dco_decode_list_phase_model(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RunListItemModel> dco_decode_list_run_list_item_model(dynamic raw);

  @protected
  List<ShieldChangeModel> dco_decode_list_shield_change_model(dynamic raw);

  @protected
  List<SquadMemberModel> dco_decode_list_squad_member_model(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  RunTimesResponse? dco_decode_opt_box_autoadd_run_times_response(dynamic raw);

  @protected
  TimeTypeModel? dco_decode_opt_box_autoadd_time_type_model(dynamic raw);

  @protected
  PaginatedRunsResponse dco_decode_paginated_runs_response(dynamic raw);

  @protected
  PhaseModel dco_decode_phase_model(dynamic raw);

  @protected
  RunListItemModel dco_decode_run_list_item_model(dynamic raw);

  @protected
  RunModel dco_decode_run_model(dynamic raw);

  @protected
  RunTimesResponse dco_decode_run_times_response(dynamic raw);

  @protected
  ShieldChangeModel dco_decode_shield_change_model(dynamic raw);

  @protected
  SquadMemberModel dco_decode_squad_member_model(dynamic raw);

  @protected
  StatusEffectEnum dco_decode_status_effect_enum(dynamic raw);

  @protected
  TimeTypeModel dco_decode_time_type_model(dynamic raw);

  @protected
  TotalTimesModel dco_decode_total_times_model(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalyticsRunTotalTimesModel sse_decode_analytics_run_total_times_model(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  RunModel sse_decode_box_autoadd_run_model(SseDeserializer deserializer);

  @protected
  RunTimesResponse sse_decode_box_autoadd_run_times_response(
    SseDeserializer deserializer,
  );

  @protected
  TimeTypeModel sse_decode_box_autoadd_time_type_model(
    SseDeserializer deserializer,
  );

  @protected
  DeleteRunResult sse_decode_delete_run_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InitializeParserOutcome sse_decode_initialize_parser_outcome(
    SseDeserializer deserializer,
  );

  @protected
  LegBreakModel sse_decode_leg_break_model(SseDeserializer deserializer);

  @protected
  LegPositionEnum sse_decode_leg_position_enum(SseDeserializer deserializer);

  @protected
  List<AnalyticsRunTotalTimesModel>
  sse_decode_list_analytics_run_total_times_model(SseDeserializer deserializer);

  @protected
  List<LegBreakModel> sse_decode_list_leg_break_model(
    SseDeserializer deserializer,
  );

  @protected
  List<PhaseModel> sse_decode_list_phase_model(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RunListItemModel> sse_decode_list_run_list_item_model(
    SseDeserializer deserializer,
  );

  @protected
  List<ShieldChangeModel> sse_decode_list_shield_change_model(
    SseDeserializer deserializer,
  );

  @protected
  List<SquadMemberModel> sse_decode_list_squad_member_model(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  RunTimesResponse? sse_decode_opt_box_autoadd_run_times_response(
    SseDeserializer deserializer,
  );

  @protected
  TimeTypeModel? sse_decode_opt_box_autoadd_time_type_model(
    SseDeserializer deserializer,
  );

  @protected
  PaginatedRunsResponse sse_decode_paginated_runs_response(
    SseDeserializer deserializer,
  );

  @protected
  PhaseModel sse_decode_phase_model(SseDeserializer deserializer);

  @protected
  RunListItemModel sse_decode_run_list_item_model(SseDeserializer deserializer);

  @protected
  RunModel sse_decode_run_model(SseDeserializer deserializer);

  @protected
  RunTimesResponse sse_decode_run_times_response(SseDeserializer deserializer);

  @protected
  ShieldChangeModel sse_decode_shield_change_model(
    SseDeserializer deserializer,
  );

  @protected
  SquadMemberModel sse_decode_squad_member_model(SseDeserializer deserializer);

  @protected
  StatusEffectEnum sse_decode_status_effect_enum(SseDeserializer deserializer);

  @protected
  TimeTypeModel sse_decode_time_type_model(SseDeserializer deserializer);

  @protected
  TotalTimesModel sse_decode_total_times_model(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analytics_run_total_times_model(
    AnalyticsRunTotalTimesModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_run_model(
    RunModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_run_times_response(
    RunTimesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_time_type_model(
    TimeTypeModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_run_result(
    DeleteRunResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_initialize_parser_outcome(
    InitializeParserOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_leg_break_model(LegBreakModel self, SseSerializer serializer);

  @protected
  void sse_encode_leg_position_enum(
    LegPositionEnum self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_analytics_run_total_times_model(
    List<AnalyticsRunTotalTimesModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_leg_break_model(
    List<LegBreakModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_phase_model(
    List<PhaseModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_run_list_item_model(
    List<RunListItemModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shield_change_model(
    List<ShieldChangeModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_squad_member_model(
    List<SquadMemberModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_run_times_response(
    RunTimesResponse? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_time_type_model(
    TimeTypeModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paginated_runs_response(
    PaginatedRunsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_phase_model(PhaseModel self, SseSerializer serializer);

  @protected
  void sse_encode_run_list_item_model(
    RunListItemModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_run_model(RunModel self, SseSerializer serializer);

  @protected
  void sse_encode_run_times_response(
    RunTimesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_change_model(
    ShieldChangeModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_squad_member_model(
    SquadMemberModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_status_effect_enum(
    StatusEffectEnum self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_time_type_model(TimeTypeModel self, SseSerializer serializer);

  @protected
  void sse_encode_total_times_model(
    TotalTimesModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
