// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Deletes a run by its ID.
///
/// # Arguments
/// - `run_id`: The ID of the run to delete.
/// - `db_path`: The path to the SQLite database.
///
/// # Returns
/// - `true` if the run was successfully deleted.
/// - `false` if there was an error.
bool deleteRunFromDb({required int runId}) =>
    RustLib.instance.api.crateApiDatabaseDeleteDeleteRunFromDb(runId: runId);
