name: profit_taker_analyzer
description: "Warframe Profit Taker analysis app."
publish_to: 'none'
version: 0.1.0+1

environment:
 sdk: '>=3.2.0-199.0.dev <4.0.0'

topics:
 - warframe
 - profit-taker
 - analysis

dependencies:
 flutter:
    sdk: flutter
 # Provider for state management
 provider: ^6.0.0
 # SVG rendering
 flutter_svg: ^0.22.0
 # Window customization
 bitsdojo_window: ^0.1.5
 # Screenshot functionality
 screenshot: ^2.1.0
 # Path provider for file access
 path_provider: ^2.1.2
 # Super clipboard for copy/paste operations
 super_clipboard: ^0.8.4
 # Shared preferences
 shared_preferences: ^2.0.8

dev_dependencies:
 flutter_test:
    sdk: flutter
 # Recommended lints for good coding practices
 flutter_lints: ^2.0.0

flutter:
 uses-material-design: true
 assets:
    - assets/
 fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
    - family: DMMono
      fonts:
        - asset: fonts/DMMono-Italic.ttf
        - asset: fonts/DMMono-Light.ttf
        - asset: fonts/DMMono-LightItalic.ttf
        - asset: fonts/DMMono-Medium.ttf
        - asset: fonts/DMMono-MediumItalic.ttf
        - asset: fonts/DMMono-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/Custom-Icons.ttf
