name: profit_taker_analyzer
description: "Warframe Profit Taker analysis app."
publish_to: "none"
version: 1.0.0-beta.4

environment:
  sdk: ">=3.2.0-199.0.dev <4.0.0"

topics:
  - warframe
  - profit-taker
  - analysis

dependencies:
  flutter:
    sdk: flutter
  
  # Splash screen
  another_flutter_splash_screen: ^1.2.1
  # Windows window control
  window_manager: ^0.4.3
  # Provider for state management
  provider: ^6.1.2
  # Shared preferences
  shared_preferences: ^2.5.1
  # SVG rendering
  flutter_svg: ^2.0.17
  # Screenshot functionality
  screenshot: ^3.0.0
  # Path provider for file access
  path_provider: ^2.1.5
  # Super clipboard for copy/paste operations
  super_clipboard: ^0.8.24
  # Settings screen
  flutter_settings_ui: ^3.0.0
  # Launch URL's
  url_launcher: ^6.3.1
  # Internationalization (i18n)
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  # Used for DateTime functions
  intl: 0.20.2
  # To be able to get path from File objects
  path: any
  # Table for run storage screen
  data_table_2: ^2.5.18
  # Analytics
  syncfusion_flutter_charts: ^29.1.35
  # Rust Core library for getting run data
  rust_core:
    path: ../rust_core
  # Used to fetch most recent app version
  http: ^1.3.0
  # Used for icons
  flutter_material_design_icons: ^1.1.7447
  # Used for selecting folder to import old JSON
  file_selector: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # App icon
    - assets/AppIcon.png
    # Icons
    - assets/icons/
    # I18n language JSON's
    - assets/i18n/en.json
    - assets/i18n/pt.json
    - assets/i18n/zh.json
    - assets/i18n/ru.json
    - assets/i18n/fr.json
    - assets/i18n/tr.json
    # Images
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
    - family: DMMono
      fonts:
        - asset: fonts/DMMono-Italic.ttf
        - asset: fonts/DMMono-Light.ttf
        - asset: fonts/DMMono-LightItalic.ttf
        - asset: fonts/DMMono-Medium.ttf
        - asset: fonts/DMMono-MediumItalic.ttf
        - asset: fonts/DMMono-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/Custom-Icons.ttf
