[package]
name = "lib_profit_taker_parser"
version = "0.1.0"
publish.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
